"""M0 system users scopes sessions and audit"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_m0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_login_throttle",
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key_hash"),
    )
    op.create_table(
        "sys_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("mobile", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("role_code", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role_code IN ('owner','manager','sales','finance','admin')", name="ck_user_role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_sys_user_is_active"), "sys_user", ["is_active"], unique=False)
    op.create_index(op.f("ix_sys_user_mobile"), "sys_user", ["mobile"], unique=False)
    op.create_index(op.f("ix_sys_user_role_code"), "sys_user", ["role_code"], unique=False)
    op.create_table(
        "activity_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("activity_type", sa.String(length=48), nullable=False),
        sa.Column("object_type", sa.String(length=48), nullable=True),
        sa.Column("object_id", sa.UUID(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["sys_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_log_activity_type"), "activity_log", ["activity_type"], unique=False)
    op.create_index(op.f("ix_activity_log_occurred_at"), "activity_log", ["occurred_at"], unique=False)
    op.create_index("ix_activity_user_time", "activity_log", ["user_id", "occurred_at"], unique=False)
    op.create_table(
        "sys_permission_scope",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("scope_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("scope_type IN ('self','team','all','custom')", name="ck_scope_type"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["sys_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_sys_permission_scope_scope_type"), "sys_permission_scope", ["scope_type"], unique=False)
    op.create_table(
        "sys_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["sys_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_sys_session_expires_at"), "sys_session", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sys_session_user_id"), "sys_session", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sys_session_user_id"), table_name="sys_session")
    op.drop_index(op.f("ix_sys_session_expires_at"), table_name="sys_session")
    op.drop_table("sys_session")
    op.drop_index(op.f("ix_sys_permission_scope_scope_type"), table_name="sys_permission_scope")
    op.drop_table("sys_permission_scope")
    op.drop_index("ix_activity_user_time", table_name="activity_log")
    op.drop_index(op.f("ix_activity_log_occurred_at"), table_name="activity_log")
    op.drop_index(op.f("ix_activity_log_activity_type"), table_name="activity_log")
    op.drop_table("activity_log")
    op.drop_index(op.f("ix_sys_user_role_code"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_mobile"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_is_active"), table_name="sys_user")
    op.drop_table("sys_user")
    op.drop_table("sys_login_throttle")
    # ### end Alembic commands ###
