"""M1 sources imports and versioned facts"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '0002_m1'
down_revision = '0001_m0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('connector_type', sa.String(length=16), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code')
    )
    op.create_table('field_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('business_type', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('specification', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'business_type', 'version')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('business_type', sa.String(length=24), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('imported_by', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('preview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('mapping_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['imported_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], ['field_mapping.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batch_data_source_id'), 'import_batch', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_import_batch_file_hash'), 'import_batch', ['file_hash'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('customer_code', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_import_batch_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'customer_code')
    )
    op.create_index(op.f('ix_customer_owner_user_id'), 'customer', ['owner_user_id'], unique=False)
    op.create_table('financial_metric_monthly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('statement_type', sa.String(length=24), nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('period_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ytd_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('begin_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('end_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_batch_id', 'metric_code')
    )
    op.create_index(op.f('ix_financial_metric_monthly_import_batch_id'), 'financial_metric_monthly', ['import_batch_id'], unique=False)
    op.create_table('financial_period',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('profit_import_batch_id', sa.UUID(), nullable=True),
    sa.Column('balance_import_batch_id', sa.UUID(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['balance_import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['profit_import_batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'period_month')
    )
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_import_batch_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_import_batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'product_code')
    )
    op.create_table('raw_import_row',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parse_status', sa.String(length=24), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_batch_id', 'sheet_name', 'row_no')
    )
    op.create_index(op.f('ix_raw_import_row_import_batch_id'), 'raw_import_row', ['import_batch_id'], unique=False)
    op.create_table('sales_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('order_no', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('sales_user_id', sa.UUID(), nullable=True),
    sa.Column('sales_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('received_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=24), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('last_import_batch_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['last_import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['sales_user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'order_no')
    )
    op.create_index(op.f('ix_sales_order_customer_id'), 'sales_order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_order_order_date'), 'sales_order', ['order_date'], unique=False)
    op.create_index(op.f('ix_sales_order_sales_user_id'), 'sales_order', ['sales_user_id'], unique=False)
    op.create_table('sales_order_line',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_name', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('line_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True),
    sa.Column('actual_cost_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_import_batch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['last_import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_order_id', 'version', 'line_no')
    )
    op.create_index(op.f('ix_sales_order_line_sales_order_id'), 'sales_order_line', ['sales_order_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_order_line_sales_order_id'), table_name='sales_order_line')
    op.drop_table('sales_order_line')
    op.drop_index(op.f('ix_sales_order_sales_user_id'), table_name='sales_order')
    op.drop_index(op.f('ix_sales_order_order_date'), table_name='sales_order')
    op.drop_index(op.f('ix_sales_order_customer_id'), table_name='sales_order')
    op.drop_table('sales_order')
    op.drop_index(op.f('ix_raw_import_row_import_batch_id'), table_name='raw_import_row')
    op.drop_table('raw_import_row')
    op.drop_table('product')
    op.drop_table('financial_period')
    op.drop_index(op.f('ix_financial_metric_monthly_import_batch_id'), table_name='financial_metric_monthly')
    op.drop_table('financial_metric_monthly')
    op.drop_index(op.f('ix_customer_owner_user_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_import_batch_file_hash'), table_name='import_batch')
    op.drop_index(op.f('ix_import_batch_data_source_id'), table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_table('field_mapping')
    op.drop_table('data_source')
    # ### end Alembic commands ###
