import {test,expect,Page} from "@playwright/test";

async function login(page:Page, role:string) {
  await page.goto("/");
  await page.getByLabel("账号",{exact:true}).fill(`demo_${role}`);
  await page.getByLabel("密码",{exact:true}).fill(process.env.DEMO_PASSWORD!);
  await page.getByRole("button",{name:"登录",exact:true}).click();
  await expect(page.getByRole("button",{name:"退出登录",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"客户与待办",exact:true}).click();
  await expect(page.getByRole("heading",{name:"客户与待办",exact:true})).toBeVisible();
}

test("M2 sales prospect, contact, followup, next-day task and opportunity",async({page},info)=>{
  const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
  await login(page,"sales");
  await page.getByRole("button",{name:"新增潜客",exact:true}).click();
  const prospect=page.getByRole("form",{name:"新增潜客"});
  await expect(prospect.getByRole("heading")).toBeInViewport();
  const name=`CRM 流程样本 ${Date.now()}`;
  const taskTitle=`明日确认预算 ${Date.now()}`;
  await prospect.getByLabel("潜客名称").fill(name);
  await prospect.getByRole("button",{name:"创建潜客"}).click();
  await expect(page.getByRole("heading",{name,exact:true})).toBeVisible();
  await page.getByRole("button",{name:"新增联系人",exact:true}).click();
  const contact=page.getByRole("form",{name:"联系人信息"});
  await expect(contact.getByRole("heading")).toBeInViewport();
  await contact.getByLabel("联系人姓名").fill("王采购");
  await contact.getByLabel("关系角色（如老板、采购）").fill("采购");
  await contact.getByLabel("联系电话").fill("test-123");
  await contact.getByRole("button",{name:"保存联系人"}).click();
  await expect(page.getByText("王采购 · 采购",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"新增跟进",exact:true}).click();
  const follow=page.getByRole("form",{name:"记录跟进"});
  await follow.getByLabel("沟通摘要").fill("需求已确认，请明日联系");
  await follow.getByLabel("已发送资料",{exact:true}).check();
  await follow.getByLabel("资料说明").fill("福利方案");
  await follow.getByLabel("下一步动作").fill(taskTitle);
  const tomorrow=new Date(Date.now()+86400000+8*3600000).toISOString().slice(0,10)+"T10:00";
  await follow.getByLabel("下次跟进时间（北京时间）").fill(tomorrow);
  await follow.getByRole("button",{name:"保存跟进与下一步"}).click();
  await expect(page.getByText("需求已确认，请明日联系",{exact:false})).toBeVisible();
  await page.getByRole("button",{name:"新增商机",exact:true}).click();
  const opp=page.getByRole("form",{name:"商机信息"});
  await opp.getByLabel("商机名称").fill("节日采购项目");
  await opp.getByLabel("预计金额（元）").fill("100.10");
  await opp.getByLabel("成交概率（0—1，如 0.7）").fill("0.5");
  await opp.getByRole("button",{name:"保存商机"}).click();
  await expect(page.getByText(/加权 50.05 元/)).toBeVisible();
  await page.getByRole("button",{name:"更新商机",exact:true}).click();
  await page.getByRole("form",{name:"商机信息"}).getByLabel("商机阶段").selectOption("quoted");
  await page.getByRole("form",{name:"商机信息"}).getByRole("button",{name:"保存商机"}).click();
  await expect(page.getByText(/已报价.*预计 100.10/)).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.screenshot({path:`../../.tools/m2-customer-${info.project.name}.png`,fullPage:true});
  await page.getByRole("button",{name:"我的待办",exact:true}).click();
  await page.getByRole("button",{name:"未来",exact:true}).click();
  const task=page.locator("article").filter({has:page.getByText(taskTitle,{exact:true})});
  await expect(task).toHaveCount(1);
  await task.getByRole("button",{name:"完成待办"}).click();
  await expect(task).toHaveCount(0);
  await page.getByRole("button",{name:"已完成",exact:true}).click();
  await expect(page.getByText(taskTitle,{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"退出登录"}).click();
  await login(page,"sales2");
  await page.getByLabel("搜索客户",{exact:true}).fill(name);
  await page.getByRole("button",{name:"搜索",exact:true}).click();
  await expect(page.getByText("暂无符合条件的客户。")).toBeVisible();
  expect(errors).toEqual([]);
});

test("M2 admin assigns imported customer, manager sees team, pool claim",async({page})=>{
  await login(page,"admin");
  const people=await page.request.get('/api/crm/people');
  const sales=(await people.json()).find((x:{username:string})=>x.username==='demo_sales');
  // Seed a prospect through the authorized sales API; no real sample database is used.
  await page.getByRole("button",{name:"退出登录"}).click();
  await login(page,"sales");
  const base=new URL(page.url()).origin;
  const r=await page.request.post('/api/crm/customers',{headers:{Origin:base},data:{customer_name:`公海流程 ${Date.now()}`}});
  expect(r.status()).toBe(201);
  const customer=(await r.json()).customer;
  await page.getByRole("button",{name:"退出登录"}).click();
  await login(page,"manager");
  await page.getByLabel("搜索客户",{exact:true}).fill(customer.customer_name);
  await page.getByRole("button",{name:"搜索",exact:true}).click();
  await page.getByRole("button",{name:"查看客户",exact:true}).click();
  await page.getByRole("button",{name:"分配／转交／公海",exact:true}).click();
  const form=page.getByRole("form",{name:"客户归属调整"});
  await form.getByLabel("新负责人").selectOption("");
  await form.getByLabel("转交原因").fill("交由公海重新跟进");
  await form.getByRole("button",{name:"确认调整归属"}).click();
  await expect(page.getByText("归属已调整，历史记录保留")).toBeVisible();
  await page.getByRole("button",{name:"退出登录"}).click();
  await login(page,"sales");
  await page.getByRole("button",{name:"客户公海",exact:true}).click();
  await page.getByRole("button",{name:"领取客户",exact:true}).click();
  await expect(page.getByRole("heading",{name:customer.customer_name,exact:true})).toBeVisible();
  const d=await page.request.get(`/api/crm/customers/${customer.id}`);
  expect((await d.json()).customer.owner_user_id).toBe(sales.id);
  await expect(page.getByText(/调整客户归属.*交由公海重新跟进/)).toBeVisible();
});
