"use client";

import { useEffect, useRef, useState } from "react";
import { currentMonth, longDate } from "./lib/format";
import { api, useData } from "./lib/api";

import type { AttentionPage, CustomerRow as Customer, FollowupRow as Follow, OrderRow as Order, Page, TaskPage, TaskRow as Task, User } from "./lib/types";
import { Icon } from "./sales/ui";
import type { Analysis, Data, DialogState, OrderDetail, PerfPreset, Performance, ProjectBoard, Route, Screen, Source, Work, WorkbenchSummary } from "./sales/types";
import { PerformanceScreen } from "./sales/performance-screen";
import { WorkbenchScreen } from "./sales/workbench-screen";
import { TasksScreen } from "./sales/tasks-screen";
import { CustomersScreen } from "./sales/customers-screen";
import { SalesDialog } from "./sales/sales-dialog";
import { AllCustomersModal, AllProductsModal, OrderDetailModal, RecentModal } from "./sales/modals";

const titles:Record<Screen,string> = {workbench:"工作台",customers:"客户",tasks:"待办",performance:"我的业绩"};
function perfRange(preset:PerfPreset,month:string):{from:string;to:string;label:string} {const [y,m]=month.split("-").map(Number);const pad=(n:number)=>String(n).padStart(2,"0");const ym=(yy:number,mm:number)=>`${yy}-${pad(mm)}-01`;if(preset==="last"){const yy=m===1?y-1:y,mm=m===1?12:m-1;return {from:ym(yy,mm),to:ym(yy,mm),label:"上月"};}if(preset==="quarter")return {from:ym(y,Math.floor((m-1)/3)*3+1),to:ym(y,m),label:"本季度"};if(preset==="year")return {from:ym(y,1),to:ym(y,m),label:"今年"};return {from:ym(y,m),to:ym(y,m),label:"本月"};}
function readRoute():Route {const [path,query=""]=window.location.hash.slice(1).split("?");const p=new URLSearchParams(query);if(path==="sales"){const s=p.get("view") as Screen;return {screen:s in titles?s:"workbench",pool:p.get("pool")==="1",customerId:p.get("customer")||undefined,q:p.get("q")||undefined,taskView:p.get("tasks")||undefined,status:p.get("status")||undefined};}if(path==="crm"){try{const e=JSON.parse(p.get("crm")||"{}");return {screen:e.tab==="tasks"?"tasks":"customers",pool:e.tab==="pool",customerId:e.customerId,taskView:e.taskView};}catch{return {screen:"customers"};}}if(path==="bi"&&p.get("tab")&&p.get("tab")!=="workbench")return {screen:"performance"};return {screen:"workbench"};}
function href(r:Route) {const p=new URLSearchParams({view:r.screen});if(r.pool)p.set("pool","1");if(r.customerId)p.set("customer",r.customerId);if(r.q)p.set("q",r.q);if(r.taskView)p.set("tasks",r.taskView);if(r.status)p.set("status",r.status);return "#sales?"+p;}

export default function SalesWorkspace({user,onSignOut}:{user:User;onSignOut:()=>Promise<void>}) {
 const [route,setRoute]=useState<Route>({screen:"workbench"}),[revision,setRevision]=useState(0),[query,setQuery]=useState(""),[offset,setOffset]=useState(0),[taskOffset,setTaskOffset]=useState(0),[taskView,setTaskView]=useState("today"),[month,setMonth]=useState(currentMonth),[source,setSource]=useState(""),[recentOffset,setRecentOffset]=useState(0),[showRecent,setShowRecent]=useState(false),[dialog,setDialog]=useState<DialogState|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [pageSize,setPageSize]=useState(20),[claimFilter,setClaimFilter]=useState(""),[poolIds,setPoolIds]=useState<string[]>([]),[levelFilter,setLevelFilter]=useState(""),[tagFilter,setTagFilter]=useState(""),[searchInput,setSearchInput]=useState("");
 const [perfPreset,setPerfPreset]=useState<PerfPreset>("this"),[perfMonths,setPerfMonths]=useState<6|12>(6),[showAllCustomers,setShowAllCustomers]=useState(false),[showAllProducts,setShowAllProducts]=useState(false),[allCustomerOffset,setAllCustomerOffset]=useState(0);
 useEffect(()=>{setOffset(0);setPoolIds([]);},[pageSize,claimFilter,levelFilter,tagFilter]);
 const searchTimer=useRef(0);
 useEffect(()=>{const restore=()=>{const r=readRoute();setRoute(r);setQuery(r.q||"");setSearchInput(r.q||"");setOffset(0);setTaskOffset(0);setTaskView(r.taskView||"today");};restore();window.addEventListener("popstate",restore);window.addEventListener("hashchange",restore);return()=>{window.removeEventListener("popstate",restore);window.removeEventListener("hashchange",restore);};},[]);
 function go(next:Route) {window.history.pushState(null,"",href(next));setRoute(next);if(next.screen==="workbench")setMonth(currentMonth());setQuery(next.q||"");setSearchInput(next.q||"");clearTimeout(searchTimer.current);setOffset(0);setTaskOffset(0);setTaskView(next.taskView||"today");setNotice("");if((next.pool||false)!==(route.pool||false))setLevelFilter(""),setTagFilter("");window.scrollTo({top:0});}
 function liveSearch(q:string) {const next:Route={screen:"customers",pool:route.pool,q:q||undefined};window.history.replaceState(null,"",href(next));setRoute(next);setQuery(q);setOffset(0);}
 const screen=route.screen;
 const [orderOffset,setOrderOffset]=useState(0),[orderId,setOrderId]=useState("");
 useEffect(()=>{setOrderOffset(0);setOrderId("");},[source,month]);
 const work=useData<Work>(["workbench","performance"].includes(screen)?`/api/bi/workbench/${user.id}?month=${month}-01`:null,revision);
 const taskData=useData<TaskPage>(screen==="tasks"?`/api/sales/tasks?view=${taskView}&limit=20&offset=${taskOffset}`:null,revision);
 const focusToday=useData<TaskPage>(screen==="workbench"?"/api/sales/tasks?view=today&limit=10":null,revision);
 const focusOverdue=useData<TaskPage>(screen==="workbench"?"/api/sales/tasks?view=overdue&limit=10":null,revision);
 const customers=useData<Page<Customer>>(screen==="customers"&&!route.customerId?`/api/sales/customers?pool=${!!route.pool}&q=${encodeURIComponent(route.q||"")}&offset=${offset}&limit=${pageSize}${route.pool&&claimFilter?`&claim=${claimFilter}`:""}${!route.pool&&levelFilter?`&level=${levelFilter}`:""}${!route.pool&&tagFilter?`&tag_id=${tagFilter}`:""}${!route.pool&&route.status?`&status=${route.status}`:""}`:null,revision);
 const recent=useData<Page<Follow>>(screen==="workbench"||showRecent?`/api/sales/recent?limit=${showRecent?20:3}&offset=${showRecent?recentOffset:0}`:null,revision);
 const sources=useData<Source[]>(["workbench","performance"].includes(screen)?"/api/bi/sources":null,revision);
 const overdue=useData<TaskPage>("/api/sales/tasks?view=overdue&limit=1",revision);
 const overdueCount=overdue.data?.counts?.overdue ?? 0;
 const tagList=useData<{id:string;tag_name:string}[]>(screen==="customers"&&!route.pool?"/api/crm/tags":null,revision);
 const currentSource=sources.data?.some(s=>s.id===source)?source:sources.data?.[0]?.id||"";
 const attention=useData<AttentionPage>(screen==="workbench"&&currentSource?`/api/bi/attention?source_id=${currentSource}`:null,revision);
 const perfRangeValue=perfRange(perfPreset,month);
 const perf=useData<Performance>(screen==="performance"&&currentSource?`/api/sales/performance?source_id=${currentSource}&from=${perfRangeValue.from}&to=${perfRangeValue.to}&months=${perfMonths}`:null,revision);
 const allCustomers=useData<Analysis>(showAllCustomers&&screen==="performance"&&currentSource?`/api/bi/sales?source_id=${currentSource}&month=${month}-01&dimension=customer&basis=verified&offset=${allCustomerOffset}`:null,revision);
 const orders=useData<Page<Order>>(screen==="performance"&&currentSource?`/api/bi/orders?source_id=${currentSource}&month=${month}-01&offset=${orderOffset}`:null,revision);
 const orderDetail=useData<OrderDetail>(orderId?`/api/data/sales/orders/${orderId}`:null,revision);
 const summary=useData<WorkbenchSummary>(screen==="workbench"&&currentSource?`/api/sales/workbench-summary?source_id=${currentSource}`:null,revision);
 const board=useData<ProjectBoard>(screen==="workbench"?"/api/sales/opportunities/board?limit=20":null,revision);
 async function run(action:()=>Promise<unknown>,message:string) {setBusy(true);setError("");try{await action();setNotice(message);setRevision(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function record(task?:Task,customer?:Customer) {setDialog({kind:"follow",task,customer});}
 function completeTask(t:Task) {setDialog({kind:"complete",task:t});}
 const states=[work,focusToday,focusOverdue,attention,taskData,customers,recent,sources,perf,allCustomers,orders,summary,board,overdue];
 return <div className="sales-shell"><aside className="sales-sidebar"><a className="sales-brand" href={href({screen:"workbench"})} onClick={e=>{e.preventDefault();go({screen:"workbench"});}}><span>齐</span><strong>好客齐鲁</strong></a><nav aria-label="主导航">{(Object.keys(titles) as Screen[]).map(key=><a key={key} href={href({screen:key})} aria-current={screen===key?"page":undefined} onClick={e=>{e.preventDefault();go({screen:key});}}><Icon name={key}/>{titles[key]}</a>)}</nav><details className="sales-account"><summary><span className="sales-avatar">{user.display_name.slice(0,1)}</span>{user.display_name} · 销售员</summary><p>{user.username}</p><button onClick={()=>run(onSignOut,"")} disabled={busy}>退出登录</button></details></aside>
 <div className="sales-content"><header className="sales-topbar"><form onSubmit={e=>{e.preventDefault();go({screen:"customers",q:query.trim()});}} role="search"><Icon name="search"/><input aria-label="搜索客户名称或联系人" placeholder="搜索客户名称或联系人" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/><button>搜索</button></form><div className="sales-topbar-right"><button className="sales-bell" aria-label={`逾期待办提醒，${overdueCount} 项`} onClick={()=>go({screen:"tasks",taskView:"overdue"})}><Icon name="bell"/>{overdueCount>0&&<span className="sales-bell-badge">{overdueCount>99?"99+":overdueCount}</span>}</button><time>{longDate()}</time></div></header>
 <main className="sales-main"><div className="sales-heading"><div><h1>{route.customerId?"客户详情":titles[screen]}</h1><p>{route.customerId?"客户资料、沟通记录与下一步安排。":screen==="workbench"?"今天先处理该做的事，再看结果。":screen==="customers"?"跟进已有客户，或从公海认养客户。":screen==="tasks"?"安排下一步，处理到期任务。":"查看个人目标完成情况与实际成交。"}</p></div>{!route.customerId&&(screen==="workbench"?<button onClick={()=>go({screen:"performance"})}>我的业绩 →</button>:screen!=="performance"&&<button className="sales-primary" onClick={()=>setDialog({kind:screen==="tasks"?"task":"follow"})}>{screen==="tasks"?"新建待办":"记录跟进"}</button>)}</div>
 {(error||states.some(s=>s.error))&&<div role="alert" className="sales-alert">{error||states.find(s=>s.error)?.error}<button onClick={()=>{setError("");setRevision(n=>n+1);}}>重试</button></div>}{notice&&<p className="sales-notice" role="status">{notice}</p>}
 {screen==="workbench"&&<WorkbenchScreen work={work} focusToday={focusToday} focusOverdue={focusOverdue} attention={attention} summary={summary} board={board} recent={recent} go={go} record={record} completeTask={completeTask} onDefer={t=>setDialog({kind:"defer",task:t})} run={run} busy={busy} onQuickSaved={m=>{setNotice(m);setRevision(n=>n+1);}} onShowRecent={()=>{setShowRecent(true);setRecentOffset(0);}}/>}
 {screen==="customers"&&<CustomersScreen route={route} customers={customers} user={user} revision={revision} offset={offset} onOffsetChange={setOffset} pageSize={pageSize} onPageSizeChange={setPageSize} claimFilter={claimFilter} onClaimFilterChange={setClaimFilter} poolIds={poolIds} onPoolIdsChange={setPoolIds} levelFilter={levelFilter} onLevelFilterChange={setLevelFilter} tagFilter={tagFilter} onTagFilterChange={setTagFilter} searchInput={searchInput} setSearchInput={setSearchInput} onSearchInput={v=>{setSearchInput(v);clearTimeout(searchTimer.current);searchTimer.current=window.setTimeout(()=>liveSearch(v.trim()),400);}} liveSearch={liveSearch} tagList={tagList} busy={busy} run={run} record={record} go={go}/>}
 {screen==="tasks"&&<TasksScreen taskData={taskData} taskOffset={taskOffset} onOffsetChange={setTaskOffset} taskView={taskView} onViewChange={key=>{setTaskView(key);setTaskOffset(0);window.history.replaceState(null,"",href({...route,taskView:key}));}} go={go} record={record} completeTask={completeTask} onDefer={t=>setDialog({kind:"defer",task:t})} run={run} busy={busy}/>}
 {screen==="performance"&&<PerformanceScreen perf={perf} sources={sources} currentSource={currentSource} onSourceChange={setSource} perfPreset={perfPreset} onPresetChange={setPerfPreset} perfMonths={perfMonths} onMonthsChange={setPerfMonths} month={month} onMonthChange={v=>{setMonth(v||currentMonth());setPerfPreset("this");}} perfRangeValue={perfRangeValue} orders={orders} orderOffset={orderOffset} onOrderOffsetChange={setOrderOffset} onOrderDetail={setOrderId} allCustomerOffset={allCustomerOffset} onAllCustomerOffsetChange={setAllCustomerOffset} onShowAllCustomers={()=>{setAllCustomerOffset(0);setShowAllCustomers(true);}} onShowAllProducts={()=>setShowAllProducts(true)} go={go}/>}
 </main></div>{orderId&&<OrderDetailModal orderDetail={orderDetail} onClose={()=>setOrderId("")}/>}{dialog&&<SalesDialog state={dialog} user={user} close={()=>setDialog(null)} saved={(message)=>{setDialog(null);setNotice(message);setRevision(n=>n+1);}} switchToFollow={(t)=>setDialog({kind:"follow",task:t})}/>}{showRecent&&<RecentModal recent={recent} recentOffset={recentOffset} onOffsetChange={setRecentOffset} onClose={()=>setShowRecent(false)} go={go}/>}{showAllCustomers&&<AllCustomersModal allCustomers={allCustomers} perfRangeValue={perfRangeValue} allCustomerOffset={allCustomerOffset} onOffsetChange={setAllCustomerOffset} onClose={()=>setShowAllCustomers(false)} go={go}/>}{showAllProducts&&<AllProductsModal perf={perf} perfRangeValue={perfRangeValue} onClose={()=>setShowAllProducts(false)}/>}</div>;
}
